### ISSUE TITLE
Typo in Cosmicord Interface

### ISSUE THREAD

**Issue by brianferri** [SudhanPlayz/Cosmicord.js#1]
In the Cosmicord typings > interfaces > Cosmicord.interface.d.ts at line 35:

```ts
/**
 * Emitted when a player is destroyed.
 */
playerDestoryed: [CosmiNode, CosmiPlayer];
```

playerDestoryed is a typo

**Comment by ItzSudhan** [comment]
hey, I'm not sure which one is a type there. Typings are auto generated by typescript compiler. Could you make a PR or something because I'm not sure what are you referring to.

https://github.com/SudhanPlayz/Cosmicord.js/blob/master/src/interfaces/Cosmicord.interface.ts#LL50C1-L50C1

**Comment by brianferri** [comment]
> hey, I'm not sure which one is a type there. Typings are auto generated by typescript compiler. Could you make a PR or something because I'm not sure what are you referring to.
> 
> https://github.com/SudhanPlayz/Cosmicord.js/blob/master/src/interfaces/Cosmicord.interface.ts#LL50C1-L50C1

Ah, i see. Then I'll make a PR asap to fix it from source
